const GET_FOOD_REQUEST = "GET_FOOD_REQUEST";
const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS";
const GET_FOOD_FAILED = "GET_FOOD_FAILED";
const SET_PAGINATION = "SET_PAGINATION";

export { GET_FOOD_FAILED, GET_FOOD_REQUEST, GET_FOOD_SUCCESS, SET_PAGINATION };
